  // --- Lektion 2 Erweiterung: weitere Kapitel direkt anhängen ---
  {
    title: "Beispiel zu relationalen Datenbanken",
    description: "Hier siehst du, wie eine typische Tabelle in einer relationalen Datenbank aussieht – und warum ein gutes Design so wichtig ist. Mit einem einfachen Beispiel erkennst du schnell, wie Probleme entstehen und wie man sie vermeiden kann.",
    list: [
      "🗂️ Was ist überhaupt eine Tabelle?",
      "  Eine Tabelle ist wie eine große Excel-Liste: Sie besteht aus Zeilen (jede Zeile steht für einen Datensatz) und Spalten (jede Spalte steht für eine Eigenschaft, zum Beispiel Name, Adresse, Produkt usw.).",
      "",
      "📝 Unser Beispiel: Stell dir vor, du willst speichern, welcher Verkäufer welches Produkt verkauft hat – und wie viel Umsatz dabei entstanden ist. Eine einfache Tabelle könnte so aussehen:",
      "",
      " VerkNr | VerkName  | PLZ   | VerkAdresse | Produktname    | Umsatz",
      " ---------------------------------------------------------------",
      " V1     | Meier     | 80331 | München     | Waschmaschine  | 11000",
      " V1     | Meier     | 80331 | München     | Herd           | 5000",
      " V1     | Meier     | 80331 | München     | Kühlschrank    | 1000",
      " V2     | Schneider | 70173 | Stuttgart   | Herd           | 4000",
      " V2     | Schneider | 70173 | Stuttgart   | Kühlschrank    | 3000",
      " V3     | Müller    | 50667 | Köln        | Staubsauger    | 1000",
      "",
      "🔍 Wo ist das Problem?",
      "  - Die Verkäuferdaten (Name, Adresse usw.) werden immer wieder wiederholt. Das nennt man Redundanz.",
      "  - Ändert sich z.B. die Adresse von Herrn Meier, muss man sie an allen Stellen ändern. Passiert das nicht überall, gibt es Widersprüche (Inkonsistenzen) in den Daten.",
      "  - Wenn ein Produkt komplett gelöscht wird (z.B. alle Zeilen mit 'Staubsauger'), verschwindet auch der Verkäufer Müller aus der Datenbank – das ist Datenverlust.",
      "",
      "❗ Warum ist das schlecht?",
      "  - Mehr Speicherplatz wird verbraucht, weil die gleichen Daten mehrfach gespeichert werden.",
      "  - Fehler passieren leichter: Adressen oder Namen werden unterschiedlich geschrieben.",
      "  - Die Datenbank ist schwerer zu pflegen und zu durchsuchen.",
      "",
      "💡 Wie macht man es besser?",
      "  - Statt alles in einer einzigen Tabelle zu speichern, teilt man die Infos auf verschiedene, logisch zusammengehörige Tabellen auf.",
      "  - Beispiel:",
      "   • Eine Tabelle für Verkäufer (jede Person nur einmal!)",
      "   • Eine Tabelle für Produkte",
      "   • Eine Tabelle für die Verkäufe (dort steht dann nur, welcher Verkäufer welches Produkt verkauft hat und wie viel Umsatz gemacht wurde)",
      "",
      "➡️ So vermeidest du Wiederholungen, sparst Speicher und schützt deine Daten vor Fehlern.",
      "",
      "🏁 Fazit:",
      "  Schon mit diesem kleinen Beispiel merkst du: Ein gutes Datenbank-Design ist wichtig, damit deine Daten sauber, sicher und leicht nutzbar bleiben. In den nächsten Abschnitten lernst du, wie man Tabellen richtig aufbaut!"
    ],
    video: "https://www.youtube.com/embed/2RlWxMRYw20"
  },
  {
    title: "Relationale Datenstrukturen – Grundbegriffe & Aufbau",
    description: "Hier lernst du die wichtigsten Begriffe und Prinzipien kennen, die jede relationale Datenbank ausmachen. Verstehe, warum in der Fachsprache oft von Relationen, Tupeln und Attributen die Rede ist – und warum das mehr ist als nur 'eine Tabelle'.",
    list: [
      "🔍 Wichtige Begriffe in relationalen Datenbanken:",
      " • Relation = Tabelle (das Grundelement einer relationalen Datenbank)",
      " • Tupel = Eine Zeile (Datensatz) in der Tabelle",
      " • Attribut = Eine Spalte (Feld) in der Tabelle",
      " • Kardinalität = Anzahl der Zeilen (Datensätze)",
      " • Grad = Anzahl der Spalten (Eigenschaften)",
      " • Primärschlüssel = Ein Feld/Attribut, das jeden Datensatz eindeutig identifiziert",
      " • Gebiet (Domain) = Die Menge aller möglichen Werte für ein Attribut (z. B. alle deutschen Städtenamen für das Attribut 'Stadt')",
      "",
      "💡 Beispiel – Lieferanten-Tabelle",
      " | LNr | Name     | Stadt      | PLZ   |",
      " |-----|----------|------------|-------|",
      " | 1   | Müller   | München    | 81724 |",
      " | 2   | Schmidt  | Regensburg | 93055 |",
      " | 3   | Maier    | Hamburg    | 20543 |",
      " | 4   | Schwarz  | Köln       | 50087 |",
      " | 5   | Weiß     | Berlin     | 11168 |",
      "",
      " • Relation: Diese gesamte Tabelle",
      " • Tupel: z. B. die Zeile mit Müller",
      " • Attribut: z. B. 'Stadt' oder 'PLZ'",
      " • Kardinalität: 5 (es gibt 5 Zeilen)",
      " • Grad: 4 (es gibt 4 Spalten)",
      "",
      "📋 Wichtige Regeln für Relationen",
      " 1. Es gibt keine doppelten Zeilen (jedes Tupel ist einzigartig)",
      " 2. Keine Reihenfolge: Die Reihenfolge der Zeilen und Spalten ist nicht fest – es ist egal, ob zuerst Müller oder Weiß in der Tabelle steht",
      " 3. Alle Werte sind 'atomar': In jedem Feld steht immer nur EIN Wert, z. B. genau EIN Städtename, nicht mehrere",
      " 4. Jedes Attribut hat einen festen 'Datentyp' oder Wertbereich ('Gebiet')",
      "",
      "⚡ Warum diese Regeln?",
      " • Sie sorgen dafür, dass die Datenbank einfach und eindeutig bleibt",
      " • Einfache physische Speicherung: Alle Zeilen sind gleich lang, neue Zeilen können einfach eingefügt/gelöscht werden",
      " • Kein Durcheinander mit doppelten Daten oder Listen in Zellen",
      " • SQL-Abfragen werden dadurch klar und vorhersehbar (z. B. gibt es kein 'zweites' oder 'siebtes' Element – Reihenfolge ist egal!)",
      "",
      "🚩 Beispiel für eine schlechte (nicht-atomare) Tabelle:",
      " | VerkNr | VerkName | Produkte                        | Umsatz |",
      " |--------|----------|---------------------------------|--------|",
      " | V1     | Meier    | Waschmaschine, Herd, Kühlschrank| 17000  |",
      "",
      " • Problem: In der Spalte 'Produkte' stehen mehrere Werte. Das ist nicht erlaubt, weil jeder Eintrag atomar sein muss.",
      " • Konsequenz: Solche Tabellen sind schwer zu verwalten und führen zu Fehlern!",
      "",
      "🏛️ Was ist eine relationale Datenbank?",
      " • Eine Sammlung von mehreren Relationen (also Tabellen), die zusammenarbeiten und sich logisch ergänzen",
      " • Nicht jede 'normale' Tabelle ist automatisch eine Relation!",
      "",
      "📚 Arten von Relationen:",
      " • Basisrelation (Basistabelle): Die eigentlichen, dauerhaft gespeicherten Tabellen (z. B. 'Kunden', 'Lieferanten')",
      " • Sicht (View): Eine virtuelle Tabelle, die nur aus einer oder mehreren Basistabellen abgeleitet wird – existiert nicht dauerhaft, sondern wird bei der Abfrage erzeugt",
      " • Abfrageergebnis: Temporäre Tabelle, die nur für die Dauer einer SQL-Abfrage entsteht",
      " • Temporäre Relation: Kurzfristig erzeugte Tabelle, meist nach dem Logout wieder gelöscht",
      "",
      "✅ SQL-Befehle, um Relationen zu erstellen oder abzufragen:",
      " • CREATE TABLE ... – neue Basistabelle anlegen",
      " • CREATE VIEW ... – neue Sicht anlegen",
      " • SELECT ... – Abfrage ausführen (ergibt temporäre Relation)",
      " • CREATE TEMPORARY TABLE ... – temporäre Relation erzeugen",
      "",
      "🎯 Fazit: Relationale Datenstrukturen sind klar geregelt – das sorgt für Übersicht, verhindert Fehler und macht SQL so mächtig und leicht verständlich!"
    ],
    video: "https://www.youtube.com/embed/UZiVj6nKSM8"
  },
  {
    title: "Primärschlüssel – Das Rückgrat jeder Tabelle",
    description: "Jede Zeile in einer Datenbanktabelle muss eindeutig identifizierbar sein – sonst gibt es Chaos! Der sogenannte Primärschlüssel ist dafür verantwortlich. Hier erfährst du, was ein Primärschlüssel ist, warum er so wichtig ist und wie man ihn auswählt.",
    list: [
      "🔑 Was ist ein Primärschlüssel?",
      " • Der Primärschlüssel ist ein Feld (oder eine Kombination mehrerer Felder), das jeden Datensatz einer Tabelle eindeutig macht.",
      " • Beispiel: In einer Lieferantentabelle kann die Spalte 'Lieferantennummer' (LNr) der Primärschlüssel sein – jede LNr kommt nur einmal vor.",
      "",
      "🧮 Warum braucht jede Tabelle einen Primärschlüssel?",
      " • Damit keine doppelten Datensätze entstehen.",
      " • Damit das Suchen, Ändern und Löschen von Einträgen gezielt und eindeutig funktioniert.",
      " • Der Primärschlüssel ist Voraussetzung für viele SQL-Operationen und Beziehungen zwischen Tabellen.",
      "",
      "👩‍🔬 Praxisbeispiel: Chemische Elemente",
      " | Protonen | Atomgewicht | Name        | Symbol |",
      " |----------|-------------|-------------|--------|",
      " | 1        | 1,0079      | Wasserstoff | H      |",
      " | 2        | 4,0026      | Helium      | He     |",
      "",
      " • Hier könnten 'Protonen', 'Name' oder 'Symbol' als Primärschlüssel dienen, weil sie jeweils eindeutig sind.",
      "",
      " • Achtung: Nicht jeder Wert ist geeignet. Z. B. könnte das 'Atomgewicht' in Zukunft bei neuen Elementen doppelt vorkommen – unsicher als Schlüssel!",
      "",
      "🔎 Fachbegriffe rund um Schlüssel",
      " • Superschlüssel: Jede Kombination von Attributen, die eine Zeile eindeutig identifiziert (oft mehr, als nötig wäre).",
      " • Schlüsselkandidat: Ein minimaler Superschlüssel (so klein wie möglich, aber immer noch eindeutig).",
      " • Primärschlüssel: Einer der Schlüsselkandidaten, der als Haupt-Identifikator gewählt wird.",
      " • Alternative Schlüssel: Die übrigen Schlüsselkandidaten (können auch genutzt werden, aber nicht als Hauptschlüssel).",
      "",
      "🎯 Regeln für einen guten Primärschlüssel:",
      " 1. Muss Eindeutigkeit garantieren (keine doppelten Werte im Schlüssel-Feld!)",
      " 2. Möglichst stabil (ändert sich nie oder sehr selten)",
      " 3. So wenige Attribute wie möglich (je kürzer, desto besser für Performance und Übersicht!)",
      " 4. Wenn möglich, ein einzelnes Feld verwenden (z. B. laufende Nummer, Kundennummer)",
      "",
      "🧩 Beispiel für zusammengesetzten Primärschlüssel:",
      " | Produktname  | Produkttyp | Bestand | Preis |",
      " |--------------|------------|---------|-------|",
      " | Staubsauger  | T06        | 25      | 498   |",
      " | Staubsauger  | T17        | 17      | 219   |",
      "",
      " • Hier reicht 'Produktname' allein nicht, weil es mehrere Typen gibt. Aber die Kombination aus 'Produktname' und 'Produkttyp' ist eindeutig → zusammengesetzter Primärschlüssel.",
      "",
      "⚠️ Vorsicht bei zusätzlichen Spalten:",
      " • Einfach eine 'Produktnummer' hinzufügen? Geht, aber erhöht die Redundanz, wenn die Kombination schon eindeutig wäre.",
      " • Oft muss man abwägen: Eindeutigkeit vs. Einfachheit vs. Speicherbedarf.",
      "",
      "💡 SQL-Praxis:",
      " • Der Primärschlüssel wird beim Erstellen einer Tabelle festgelegt: z. B. PRIMARY KEY (Produktname, Produkttyp)",
      " • Bei einer Suche nach dem Primärschlüssel (z. B. Produktname = 'Staubsauger', Produkttyp = 'T06') gibt es maximal eine passende Zeile – das macht viele Operationen effizient!",
      "",
      "✅ Fazit: Der Primärschlüssel ist das Herzstück jeder Relation. Gut gewählt, sorgt er für Ordnung, Performance und saubere Datenbankanwendungen!"
    ],
    video: "https://www.youtube.com/embed/wSEK8C0N9UQ"
  },
  {
    title: "Relationale Integritätsregeln – Saubere Daten garantiert!",
    description: "Datenbanken sollen nicht nur Daten speichern, sondern auch dafür sorgen, dass die gespeicherten Informationen korrekt und widerspruchsfrei sind. Damit das klappt, gibt es zwei zentrale Regeln für jede relationale Datenbank: die Entitäts- und die Referenz-Integrität.",
    list: [
      "🧩 Was ist Integrität?",
      " • Integrität heißt: Die Daten in der Datenbank sind immer korrekt und stimmen mit der Realität überein.",
      "",
      "Es gibt vier Arten von Integrität:",
      " • Physische Integrität: Die Daten sind auf der Festplatte vollständig und unverfälscht gespeichert.",
      " • Ablaufintegrität: Programme, die auf die Datenbank zugreifen, arbeiten korrekt (z. B. keine Überlappung bei mehreren Benutzern).",
      " • Zugriffsberechtigung: Nur berechtigte Personen dürfen bestimmte Daten sehen oder ändern.",
      " • Semantische Integrität: Die gespeicherten Werte sind sinnvoll (z. B. kein Gehalt = -1000 oder 500 Stunden/Woche).",
      "",
      "Aber in relationalen Datenbanken sind vor allem zwei Integritätsregeln wichtig:",
      "",
      "🔒 1. Entitäts-Integrität (Regel für Primärschlüssel)",
      " • Jeder Datensatz (Tupel) braucht einen gültigen Primärschlüssel.",
      " • Kein Feld im Primärschlüssel darf leer (NULL) sein!",
      " • Beispiel: Jeder Kunde in einer Kundentabelle braucht eine eindeutige Kundennummer – sonst könnte man ihn nicht mehr eindeutig zuordnen.",
      " • Auch bei zusammengesetzten Schlüsseln (z. B. [Produktname, Produkttyp]) darf KEIN Teil leer bleiben.",
      "",
      "🚦 2. Referenz-Integrität (Regel für Fremdschlüssel)",
      " • Ein Fremdschlüssel ist ein Feld, das auf einen Primärschlüssel in einer anderen Tabelle verweist.",
      " • Wichtig: Jeder Wert im Fremdschlüssel-Feld muss es wirklich als Primärschlüssel in der Zieltabelle geben (oder leer sein).",
      " • Beispiel: In einer Auftragstabelle steht die Kundennummer. Die Nummer muss es auch wirklich in der Kundentabelle geben!",
      "",
      " • Wenn du zum Beispiel einen Auftrag auf einen Kunden verweist, der gelöscht wurde, ist die Referenz-Integrität verletzt.",
      " • SQL und moderne Datenbanken sorgen automatisch dafür, dass so etwas nicht passiert.",
      "",
      "💡 Was passiert beim Löschen oder Ändern von Daten?",
      " • Wenn z. B. ein Kunde gelöscht wird, auf den noch Aufträge verweisen, gibt es verschiedene Möglichkeiten (SQL-Einstellungen):",
      "  - NO ACTION: Das Löschen wird nicht erlaubt, solange noch Fremdschlüssel auf diesen Kunden zeigen.",
      "  - CASCADE: Alle Aufträge, die zu diesem Kunden gehören, werden automatisch mit gelöscht.",
      "  - SET NULL: Im Auftrag wird der Kundenschlüssel auf NULL gesetzt (nur erlaubt, wenn das Feld NULL akzeptiert).",
      "",
      "📦 Fazit:",
      " • Ohne diese Regeln könnte man Daten nicht mehr zuverlässig finden, zuordnen oder kontrollieren.",
      " • Sie sorgen für Ordnung und schützen vor Datenchaos – egal wie groß die Datenbank wird.",
      "",
      "✅ Merke: Integrität ist das Fundament für vertrauenswürdige und nutzbare Datenbanken!"
    ],
    video: "https://www.youtube.com/embed/gWkD_1mRFWw"
  },
  {
    title: "Relationale Algebra – Das Werkzeug für Datenbank-Abfragen",
    description: "Die relationale Algebra ist das mathematische Fundament hinter SQL-Abfragen. Mit ihr lassen sich Daten aus mehreren Tabellen auf unterschiedlichste Weise kombinieren, filtern und anzeigen – wie mit einem Baukasten für Daten!",
    list: [
      "🔬 Was ist die relationale Algebra?",
      " • Eine Sammlung von Rechen-Regeln (Operatoren), um mit Tabellen (Relationen) zu arbeiten.",
      " • Vergleichbar mit Mathe-Operatoren wie +, -, ×, ÷, aber für Tabellen statt Zahlen.",
      " • Die Grundlage für moderne Datenbanksprachen wie SQL.",
      "",
      "🛠️ Warum brauche ich das?",
      " • Mit den Operatoren der relationalen Algebra kann man jede Datenbankabfrage bauen – egal wie komplex!",
      " • Hilft zu verstehen, was SQL intern macht und wie Daten optimal verarbeitet werden.",
      "",
      "👾 Die wichtigsten Operatoren – Einfach erklärt",
      "",
      "1️⃣ Vereinigung (∪) – „Alles zusammen!“",
      " • Kombiniert zwei Tabellen zu einer – alle Datensätze aus beiden, aber doppelte nur einmal.",
      " • Beispiel: Alle Kunden aus Berlin ODER Hamburg = KundenBerlin ∪ KundenHamburg",
      "",
      "2️⃣ Schnitt (∩) – „Was haben beide gemeinsam?“",
      " • Zeigt nur die Datensätze, die in beiden Tabellen vorkommen.",
      " • Beispiel: Wer ist Kunde in Berlin UND Hamburg?",
      "",
      "3️⃣ Differenz (∖) – „Was ist nur hier drin?“",
      " • Zeigt alle Datensätze, die in Tabelle 1 stehen, aber NICHT in Tabelle 2.",
      " • Beispiel: Kunden aus Berlin, die NICHT aus Hamburg sind = KundenBerlin ∖ KundenHamburg",
      "",
      "4️⃣ Projektion (π) – „Spalten aussuchen“",
      " • Wählt bestimmte Spalten (Attribute) aus einer Tabelle aus.",
      " • Beispiel: Nur die Namen und PLZ aller Kunden anzeigen = π{Name, PLZ}(Kunden)",
      "",
      "5️⃣ Restriktion (σ) – „Zeilen filtern“",
      " • Filtert Zeilen nach einer Bedingung (z.B. nur alle Kunden in Berlin).",
      " • Beispiel: Nur Kunden aus München = σ{Ort='München'}(Kunden)",
      "",
      "6️⃣ Kreuzprodukt (×) – „Alles mit allem kombinieren“",
      " • Kombiniert JEDE Zeile aus Tabelle 1 mit JEDE Zeile aus Tabelle 2 – selten sinnvoll allein, aber Basis für Verbindungen.",
      "",
      "7️⃣ Verbund (⨝) – auch Join genannt",
      " • Verbindet zwei Tabellen, die ein gemeinsames Feld haben (z. B. Kunden und Bestellungen über Kundennummer).",
      " • Beispiel: Zeige zu jeder Bestellung auch den Kundennamen.",
      "",
      "8️⃣ Division (÷) – „Wer erfüllt ALLE Bedingungen?“",
      " • Spezialoperator, um z. B. Lieferanten zu finden, die ALLE gesuchten Teile liefern können.",
      "",
      "9️⃣ Umbenennung (ρ)",
      " • Gibt Tabellen oder Spalten neue Namen, damit sie besser kombiniert werden können.",
      "",
      "💡 Gut zu wissen:",
      " • Mit diesen 9 Operatoren kann man alle Datenbankabfragen mathematisch beschreiben.",
      " • Ergebnis jeder Operation ist immer wieder eine Tabelle – man kann sie beliebig kombinieren.",
      "",
      "🎓 Kleine Beispiele:",
      " • Kunden aus Berlin ODER Hamburg: KundenBerlin ∪ KundenHamburg",
      " • Nur die Namen aus der Kundentabelle: π{Name}(Kunden)",
      " • Nur Kunden mit PLZ 80331: σ{PLZ=80331}(Kunden)",
      "",
      "🚦 Fazit:",
      " • Die relationale Algebra ist die Theorie hinter SQL und gibt uns die Werkzeuge an die Hand, um Daten flexibel zu verknüpfen, filtern und auszugeben.",
      " • Mit diesen Werkzeugen kann man aus einer Datenbank fast alles herausholen – der Fantasie sind kaum Grenzen gesetzt!",
      "",
      "🌐 Mehr zu SQL und wie das praktisch aussieht, kommt in den nächsten Kapiteln!"
    ],
    video: "https://www.youtube.com/embed/9PpWZ8gKa8c"
  }